
[workspace]
resolver = "2"

members = [
  #
  "launcher",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/unionlabs/tools"

[workspace.lints.rust]

[workspace.lints.clippy]
