cargo-features = ["edition2024"]

[package]
name = "launcher"
version = "0.1.0"
description = "Launches vscode server in the browser"
edition.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
