cargo-features = ["edition2024"]

[package]
name = "launcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
description = "Launches vscode server in the browser"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[lints]
workspace = true
